apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: act6-serve
spec:
  type: ClusterIP
  selector:
    app: vllm-server
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
