apiVersion: v1
kind: ServiceAccount
metadata:
  name: embed-worker
  namespace: act2-embeddings
  annotations:
    iam.gke.io/gcp-service-account: spot-demo-embed@example-sandbox.iam.gserviceaccount.com
