// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package render

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/cwest/gke-spot-playbook/advisor/internal/analyze"
)

// ClusterConfig emits the env file infra scripts source to create the cluster
// in the advisor-chosen region.
func ClusterConfig(a *analyze.Analysis) ([]byte, error) {
	if len(a.Candidates) == 0 {
		return nil, fmt.Errorf("no candidates; cannot choose a region")
	}
	// Prefer kept candidates; when every candidate was dropped, fall back to the
	// dropped set (with a loud warning) rather than refusing to render. Candidates
	// are relied on to be kept-first-by-composite (guaranteed by RunRender's
	// re-sort) so the first match is the strongest region.
	region, zoneSet := pickRegion(a.Candidates, false)
	belowBand := false
	if region == "" {
		region, zoneSet = pickRegion(a.Candidates, true)
		belowBand = true
	}
	zones := make([]string, 0, len(zoneSet))
	for z := range zoneSet {
		zones = append(zones, z)
	}
	sort.Strings(zones)
	var b bytes.Buffer
	fmt.Fprintf(&b, "# Generated by capacity-advisor at %s\n", a.GeneratedAt.UTC().Format(time.RFC3339))
	if belowBand {
		b.WriteString("# WARNING: region chosen from below-band candidates.\n")
	}
	fmt.Fprintf(&b, "PROJECT=%s\n", a.Project)
	fmt.Fprintf(&b, "REGION=%s\n", region)
	fmt.Fprintf(&b, "ZONES=%s\n", strings.Join(zones, ","))
	return b.Bytes(), nil
}

// targetRegion returns the region the advisor will build the cluster in: the
// region of the first (highest-ranked) candidate. Candidates are assumed
// kept-first-by-composite (guaranteed by RunRender's re-sort) so the first match
// is the strongest region. When includeDropped is false only kept candidates are
// considered; the empty string is returned if none qualify. ComputeClass and
// ClusterConfig share this so the two artifacts can never disagree on region.
func targetRegion(cands []analyze.Candidate, includeDropped bool) string {
	for _, c := range cands {
		if c.Dropped && !includeDropped {
			continue
		}
		return c.Region
	}
	return ""
}

// pickRegion returns the target region and the set of its zones. Candidates are
// assumed kept-first-by-composite (guaranteed by RunRender's re-sort). When
// includeDropped is false only kept candidates are considered; the empty string
// is returned if none qualify.
func pickRegion(cands []analyze.Candidate, includeDropped bool) (string, map[string]bool) {
	region := targetRegion(cands, includeDropped)
	zoneSet := map[string]bool{}
	if region == "" {
		return region, zoneSet
	}
	for _, c := range cands {
		if c.Dropped && !includeDropped {
			continue
		}
		if c.Region == region {
			zoneSet[c.Zone] = true
		}
	}
	return region, zoneSet
}
