// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package render turns an Analysis into deployable artifacts.
package render

import (
	"bytes"
	"fmt"
	"math"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/cwest/gke-spot-playbook/advisor/internal/analyze"
	"github.com/cwest/gke-spot-playbook/advisor/internal/machinetype"
)

type rung struct {
	MachineType string
	Zones       []string
	Score       int
	Composite   float64
	// GPUCount is the attached-L4 count for gpu-kind rungs; 0 for cpu rungs
	// (which suppresses the accelerator block so CPU output is unchanged).
	GPUCount int
	// Widened is set when every sharded zone for this shape was evidence-dry
	// and the rung was rebuilt from the zones we never sampled.
	Widened bool
	// Exhausted is set when even widening found nothing; the rung keeps its
	// original zones so the ladder degrades rather than breaking.
	Exhausted bool
}

// flexRung is the DWS flex-start fallback appended to gpu classes. It needs the
// accelerator count too so NAP can attach L4s when it creates the flex pool.
type flexRung struct {
	MachineType string
	GPUCount    int
}

var ccTmpl = template.Must(template.New("cc").Parse(`# Generated by capacity-advisor at {{.GeneratedAt}} — do not edit by hand.
{{- if .Warning}}
{{.Warning}}
{{- end}}
# Profile: {{.Profile}} | project: {{.Project}} | allowed regions: {{.Regions}}
# Target region: {{.Region}} (rungs filtered to this region)
{{- range .Rungs}}
# rung {{.MachineType}} score={{.Score}} composite={{printf "%.3f" .Composite}} zones={{.Zones}}{{if .Widened}} widened=evidence{{end}}{{if .Exhausted}} exhausted=all-zones-dry{{end}}
{{- end}}
apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: {{.Name}}
spec:
  nodePoolAutoCreation:
    enabled: true
  activeMigration:
    optimizeRulePriority: true
  priorities:
{{- range .Rungs}}
  - machineType: {{.MachineType}}
    spot: true
{{- if .GPUCount}}
    gpu:
      type: nvidia-l4
      count: {{.GPUCount}}
{{- end}}
    priorityScore: {{.Score}}
    location:
      zones: [{{range $i, $z := .Zones}}{{if $i}}, {{end}}{{$z}}{{end}}]
{{- end}}
{{- if .FlexRung}}
  - machineType: {{.FlexRung.MachineType}}
    priorityScore: 1
{{- if .FlexRung.GPUCount}}
    gpu:
      type: nvidia-l4
      count: {{.FlexRung.GPUCount}}
{{- end}}
    maxRunDurationSeconds: 86400
    flexStart:
      enabled: true
      nodeRecycling:
        leadTimeSeconds: 3600
{{- end}}
  whenUnsatisfiable: {{.WhenUnsatisfiable}}
`))

// ComputeClass renders a class with every never-sharded widen target trusted:
// the one-shot CLI/advise/report paths have no reconcile state to consult, so a
// probe gate there would be meaningless. It is a thin wrapper over
// ComputeClassGated with an always-confirm gate, which keeps this path
// byte-for-byte identical to before the gate existed.
func ComputeClass(a *analyze.Analysis, className string, maxRungs int) ([]byte, error) {
	return ComputeClassGated(a, className, maxRungs, func(string, string) bool { return true })
}

// ComputeClassGated is ComputeClass with a probe gate on the never-sharded
// widening seam. confirmedZone(mt, zone) reports whether a live probe has
// confirmed capacity for a universe zone the shape was never sharded into; only
// confirmed zones are widened onto. The reconciler passes its live confirmation
// track here so an all-evidence-dry rung widens off measured capacity rather than
// the stale prior. See buildRungs.
func ComputeClassGated(a *analyze.Analysis, className string, maxRungs int, confirmedZone func(mt, zone string) bool) ([]byte, error) {
	if len(a.Candidates) == 0 {
		return nil, fmt.Errorf("no candidates to render; refusing to render %s", className)
	}
	// When every candidate was dropped (all below the 0.4 obtainability band),
	// the spec requires we still render, promoting the floor with a loud warning
	// rather than refusing. Build rungs from the dropped set in that case.
	includeDropped := !hasKept(a)
	// The ComputeClass is applied to ONE regional cluster — the region
	// ClusterConfig chooses. Rungs must be confined to that region so GKE's
	// location.zones are all in-region; shared targetRegion keeps them agreed.
	region := targetRegion(a.Candidates, includeDropped)
	rungs := buildRungs(a, maxRungs, includeDropped, region, confirmedZone)
	// GPU classes must attach an explicit accelerator block to every rung: NAP
	// needs the gpu: signal to attach an L4, otherwise node auto-creation fails
	// with no.scale.up.unexpected.error (see demo/act2/runbook.md Deviations).
	if a.Kind == "gpu" {
		for i := range rungs {
			n, err := machinetype.Units(rungs[i].MachineType, "gpu")
			if err != nil {
				return nil, err
			}
			rungs[i].GPUCount = int(n)
		}
	}
	warning := ""
	if includeDropped {
		warning = `# WARNING: ALL candidates scored below the 0.4 obtainability band ("Low").` + "\n" +
			"# Spot capacity is unlikely to be obtainable; the fallback floor will carry the load."
	}
	data := struct {
		GeneratedAt, Warning, Profile, Project, Regions, Region, Name, WhenUnsatisfiable string
		FlexRung                                                                         *flexRung
		Rungs                                                                            []rung
	}{
		GeneratedAt: a.GeneratedAt.UTC().Format(time.RFC3339),
		Warning:     warning,
		Profile:     a.Profile, Project: a.Project,
		Regions: strings.Join(a.AllowedRegions, ", "),
		Region:  region,
		Name:    className, Rungs: rungs,
		WhenUnsatisfiable: "ScaleUpAnyway",
	}
	if a.Kind == "gpu" {
		data.WhenUnsatisfiable = "DoNotScaleUp"
		// Flex-start (DWS) fallback on the best shape. The CRD requires
		// priorityScore be set on all priorities or none, and each score must be
		// >= 1; the spot rungs carry scores, so the flex rung must too. Invariant:
		// spot rungs score >= 2 in every path (including the all-low fallback);
		// flexStart is pinned at 1 so it is always the last resort. It carries the
		// same accelerator block as its spot counterpart so NAP can attach L4s.
		data.FlexRung = &flexRung{
			MachineType: rungs[0].MachineType,
			GPUCount:    rungs[0].GPUCount,
		}
	}
	var buf bytes.Buffer
	if err := ccTmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// hasKept reports whether any candidate survived scoring.
func hasKept(a *analyze.Analysis) bool {
	for _, c := range a.Candidates {
		if !c.Dropped {
			return true
		}
	}
	return false
}

// buildRungs groups candidates by machine type (ranked order preserved),
// unioning zones, scoring proportionally to the best composite. Only candidates
// in the target region are used, since the ComputeClass is applied to one
// regional cluster; out-of-region zones are invalid for GKE location.zones. A
// machine type present only outside the region simply yields no rung. Normally
// only kept candidates are used; when includeDropped is set (all-dropped
// fallback) every candidate is grouped so the floor still renders.
//
// Evidence-dry zones are removed from their rung. When that empties a rung, it
// is widened to the in-region zones we never sharded for that shape: a stockout
// in the zones the advice API happened to sample is not a region-wide stockout,
// and Plan 3 needed exactly this widening by hand.
//
// A widened rung keeps the crushed composite the evidence produced even though
// the zones that earned it are no longer on the rung. That is deliberate and
// conservative: the widening targets are precisely the zones the advice API
// never sampled, so scoring them back up would be trusting capacity nobody has
// measured. A widened rung is a place to try, not a place we expect to win.
func buildRungs(a *analyze.Analysis, maxRungs int, includeDropped bool, region string, confirmedZone func(mt, zone string) bool) []rung {
	var order []string
	byType := map[string]*rung{}
	best := 0.0
	// widen: shape -> the in-region universe zones it would widen to when all of
	// its own sharded zones go dry. See WidenTargets for why it is built above
	// the Dropped filter.
	widen := WidenTargets(a, region)
	dry := map[string]map[string]bool{} // machineType -> zone -> dry
	pinned := map[string][]string{}     // machineType -> zones as sharded
	for _, c := range a.Candidates {
		if c.Dropped && !includeDropped {
			continue
		}
		if c.Region != region {
			continue
		}
		if best == 0 {
			best = c.Composite
		}
		r, ok := byType[c.MachineType]
		if !ok {
			if len(order) >= maxRungs {
				continue
			}
			r = &rung{MachineType: c.MachineType, Composite: c.Composite}
			byType[c.MachineType] = r
			order = append(order, c.MachineType)
		}
		pinned[c.MachineType] = append(pinned[c.MachineType], c.Zone)
		if c.EvidenceDry {
			if dry[c.MachineType] == nil {
				dry[c.MachineType] = map[string]bool{}
			}
			dry[c.MachineType][c.Zone] = true
			continue
		}
		r.Zones = append(r.Zones, c.Zone)
	}
	var out []rung
	for _, mt := range order {
		r := byType[mt]
		if len(r.Zones) == 0 {
			// Every sharded zone for this shape is dry. Widen to the zones we
			// never sampled — but only to those a live probe has confirmed, so we
			// widen off measured capacity rather than the stale prior. An
			// unconfirmed target is held off (the reconciler probes it); the
			// one-shot paths pass an always-confirm gate, so they widen as before.
			for _, z := range widen[mt] {
				if !dry[mt][z] && confirmedZone(mt, z) {
					r.Zones = append(r.Zones, z)
				}
			}
			r.Widened = len(r.Zones) > 0
		}
		if len(r.Zones) == 0 {
			// Nowhere left to go. A priority with no zones is invalid, and the
			// rule is never to degrade a working ladder, so keep the shape's
			// original zones and mark the rung so the operator can see why.
			r.Zones = append(r.Zones, pinned[mt]...)
			r.Exhausted = true
		}
		sort.Strings(r.Zones)
		r.Zones = dedup(r.Zones)
		out = append(out, *r)
	}
	for i := range out {
		if best > 0 {
			// Floor is 2, not 1: the gpu class appends a flexStart rung with a
			// fixed priorityScore of 1, and spot must always outrank it.
			out[i].Score = int(math.Max(2, math.Round(1000*out[i].Composite/best)))
		} else {
			// All-low path: every composite is 0, so scale-by-best is undefined.
			// Preserve rank order with synthetic descending scores that stay
			// strictly above the flex rung's 1.
			out[i].Score = 2 + (len(out) - 1 - i)
		}
	}
	return out
}

// WidenTargets maps each in-region shape to the sorted in-region zones it would
// widen to when all of its own sharded zones go evidence-dry: the universe of
// in-region zones minus the zones this shape was actually sharded into.
//
// The universe is built ABOVE the Dropped filter on purpose: a zone mentioned
// only by a dropped candidate is still a real in-region zone this shape was
// never sharded into, so it is a legitimate place to widen to. Dropping it would
// shrink the escape hatch for exactly the analyses that most need one.
//
// buildRungs consults a shape's entry only from its all-dry branch, but the map
// is built for every shape so the reconciler can enumerate widen candidates to
// probe without re-deriving the universe.
func WidenTargets(a *analyze.Analysis, region string) map[string][]string {
	universe := map[string]bool{}
	sharded := map[string]map[string]bool{}
	var order []string
	for _, c := range a.Candidates {
		if c.Region != region {
			continue
		}
		universe[c.Zone] = true
		if sharded[c.MachineType] == nil {
			sharded[c.MachineType] = map[string]bool{}
			order = append(order, c.MachineType)
		}
		sharded[c.MachineType][c.Zone] = true
	}
	out := make(map[string][]string, len(order))
	for _, mt := range order {
		var zs []string
		for z := range universe {
			if !sharded[mt][z] {
				zs = append(zs, z)
			}
		}
		sort.Strings(zs)
		out[mt] = zs
	}
	return out
}

func dedup(xs []string) []string {
	out := xs[:0]
	for i, x := range xs {
		if i == 0 || x != xs[i-1] {
			out = append(out, x)
		}
	}
	return out
}
